version: '3.8'

services:
  postgres-vendas:
    image: postgres:15
    container_name: postgres-vendas
    restart: always
    environment:
      POSTGRES_DB: vendasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata-vendas:/var/lib/postgresql/data

  venda-app:
    build: .
    container_name: venda-app
    depends_on:
      - postgres-vendas
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-1.czmuka4aqktq.us-east-1.rds.amazonaws.com:5432/postgres
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"

volumes:
  pgdata-vendas:
